version: "3.8"

services:
  node-server:
    build: ./node-server
    ports:
      - "8001:8001"
    volumes:
      - ./node-server:/app
    command: npm run dev

  python-server:
    build: ./python-server
    ports:
      - "8000:8000"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anythink-market
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./python-server:/app
