services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./node-server:/app
    command: ["yarn", "start"]

  simple-express-server:
    build:
      context: ./simple-express-server
      dockerfile: Dockerfile
    ports:
      - 8002:8001
    volumes:
      - ./simple-express-server:/usr/src/app
    command: ["yarn", "start"]
