version: '3.8'

services:
  python-server:
    build: ./python-server
    ports:
      - "8000:8000"
    volumes:
      - ./python-server:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  node-server:
    build: ./node-server
    ports:
      - "8001:8001"
    volumes:
      - ./node-server:/app
    command: yarn start
