version: "3.8"

services:
  node-server:
    build: ./node-server
    ports:
      - "8001:8001"
    volumes:
      - ./node-server:/app
    command: npm run dev

  python-server:
    build: ./python-server
    ports:
      - "8000:8000"
    volumes:
      - ./python-server:/app
